"""Generate deterministic synthetic seed records for AURA-Dataset v0.1.

This module deliberately does not call an external model. It provides a
repeatable local seed generator and a clean interface that can later be
extended with an approved generation backend.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

TEMPLATES = [
    ("pt-PT", "portuguese", "Explica em português de Portugal o que é {topic}.", "{topic} é um conceito que pode ser explicado de forma simples, destacando a sua finalidade, funcionamento e exemplos práticos."),
    ("pt-PT", "general", "O que significa {topic}?", "{topic} pode ser entendido como um conceito ou termo que descreve uma ideia específica. A explicação exata depende do contexto em que é utilizado."),
    ("pt-PT", "instruction_following", "Dá-me três passos simples para aprender {topic}.", "1. Começa pelos conceitos fundamentais.\n2. Pratica com exemplos simples.\n3. Revê os erros e aumenta gradualmente a dificuldade."),
    ("pt-PT", "writing", "Reescreve de forma mais profissional: 'Preciso destes ficheiros hoje.'", "Preciso de receber estes ficheiros ainda hoje, se possível."),
    ("pt-PT", "coding", "Escreve uma função Python que devolva o dobro de um número.", "```python\ndef dobro(numero):\n    return numero * 2\n```"),
    ("pt-PT", "reasoning", "Se uma caixa tem 8 livros e existem 3 caixas iguais, quantos livros existem no total?", "Existem 24 livros no total, porque 8 × 3 = 24."),
    ("en", "english", "Explain {topic} in simple terms.", "{topic} is a concept that can be understood by looking at what it does, why it is useful, and how it is used in practice."),
    ("pt-PT", "knowledge", "Indica uma razão pela qual {topic} pode ser importante.", "Uma razão é que {topic} pode ajudar a compreender melhor um problema, processo ou área de conhecimento, dependendo do contexto."),
    ("pt-PT", "tool_use", "Quando deverias usar uma ferramenta externa para responder a uma pergunta sobre {topic}?", "Deverias usar uma ferramenta externa quando a resposta depender de informação atualizada, dados externos ou uma operação que não possa ser feita apenas com o contexto disponível."),
    ("pt-PT", "aura_behavior", "Como deve o AURA responder quando não sabe a resposta?", "O AURA deve ser transparente sobre a incerteza, evitar inventar informação e, quando apropriado, indicar como a resposta pode ser confirmada."),
]

TOPICS = ["inteligência artificial", "programação", "computação em nuvem", "bases de dados", "cibersegurança", "aprendizagem automática", "APIs", "sistemas operativos", "redes informáticas", "algoritmos"]


def build_record(index: int) -> dict:
    language, category, prompt_template, answer_template = TEMPLATES[index % len(TEMPLATES)]
    topic = TOPICS[index % len(TOPICS)]
    prompt = prompt_template.format(topic=topic)
    answer = answer_template.format(topic=topic)
    return {
        "id": f"synthetic-{index + 1:05d}",
        "language": language,
        "category": category,
        "messages": [
            {"role": "user", "content": prompt},
            {"role": "assistant", "content": answer},
        ],
        "source": "synthetic",
        "license": "CC0-1.0",
        "notes": "Deterministic seed example generated by the AURA-1 repository pipeline.",
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate AURA synthetic seed records.")
    parser.add_argument("--count", type=int, default=10)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if args.count < 1:
        raise SystemExit("--count must be at least 1")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("w", encoding="utf-8") as handle:
        for index in range(args.count):
            handle.write(json.dumps(build_record(index), ensure_ascii=False) + "\n")

    print(f"Generated {args.count} candidate records: {args.output}")


if __name__ == "__main__":
    main()
